trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  githubRepoUrl: 'https://github.com/GuyMicciche/jwmediaconverter' 

steps:
- checkout: none

- script: |
    git init
    git remote add origin $(githubRepoUrl)
    git fetch origin main
    git checkout -b main origin/main
  displayName: 'Fetch from GitHub'

- script: |
    git remote add azure https://$(AZURE_DEVOPS_PAT)@dev.azure.com/kingguy/jwmediaconverter/_git/jwmediaconverter
    git push azure main --force
  displayName: 'Push to Azure DevOps'
  env:
    AZURE_DEVOPS_PAT: $(AZURE_DEVOPS_PAT)

