trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  githubRepoUrl: 'https://github.com/GuyMicciche/jwmediaconverter'
  azureDevOpsRepoUrl: 'dev.azure.com/kingguy.visualstudio.com/jwmediaconverter/_git/jwmediaconverter'

steps:
- script: |
    git init
    git remote add origin $(githubRepoUrl)
    git fetch origin main
    git checkout -b main origin/main
  displayName: 'Fetch from GitHub'

# Push to Azure DevOps using System.AccessToken for authentication
- script: |
    git remote add azure https://$(System.AccessToken)@$(azureDevOpsRepoUrl)
    git push azure main --force
  displayName: 'Push to Azure DevOps'
  env:
    SYSTEM_ACCESSTOKEN: $(System.AccessToken) # Azure DevOps system access token