trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
# Step 1: Fetch latest changes from GitHub
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      git clone https://github.com/GuyMicciche/jwmediaconverter.git
      cd jwmediaconverter
      git checkout main
      git pull origin main

# Step 2: Push changes to Azure DevOps Repository
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      git remote add azure https://$(AZURE_DEVOPS_PAT)@dev.azure.com/kingguy/jwmediaconverter/_git/jwmediaconverter
      git push azure main

# Step 3: Clean up cloned GitHub repository folder
- task: DeleteFiles@1
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)/jwmediaconverter'

