trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  githubRepoUrl: 'https://github.com/GuyMicciche/jwmediaconverter'
  azureDevOpsRepoUrl: 'https://kingguy.visualstudio.com/jwmediaconverter/_git/jwmediaconverter'

steps:
- script: |
    git init
    git remote add origin $(githubRepoUrl)
    git fetch origin main
    git checkout -b main origin/main
  displayName: 'Fetch from GitHub'

- script: |
    git remote add azure $(azureDevOpsRepoUrl)
    git push azure main --force
  displayName: 'Push to Azure DevOps'