# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - jwmediaconverter

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
      
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install --upgrade setuptools

      - name: Create bin directory
        run: mkdir -p ./bin

      - name: Download and extract FFMPEG to app/bin
        run: |
          mkdir -p ./temp_ffmpeg
          wget -O ./temp_ffmpeg/ffmpeg.tar.xz https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-amd64-static.tar.xz
          tar -xf ./temp_ffmpeg/ffmpeg.tar.xz --strip-components=1 -C ./temp_ffmpeg
          rm -rf ./temp_ffmpeg/ffmpeg.tar.xz
          # Move the ffmpeg executable to the bin directory without deleting other files like mkvmerge
          mv ./temp_ffmpeg/ffmpeg ./app/bin/
          # Clean up the temporary folder
          rm -rf ./temp_ffmpeg

      - name: Collect data files from jieba and pypinyin
        run: |
          mkdir -p ./collected_data/jieba
          mkdir -p ./collected_data/pypinyin
          cp -r $(python -c 'import jieba; print(jieba.__path__[0])')/* ./collected_data/jieba/
          cp -r $(python -c 'import pypinyin; print(pypinyin.__path__[0])')/* ./collected_data/pypinyin/

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            release.zip
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_489F6D2202A744CD9651D569D5BFEAA2 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_5A0196A6EB1D446689BBDD361BC0D23A }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_DBB36FEF42C04D7487700C8A7469D5D7 }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'jwmediaconverter'
          slot-name: 'Production'
          startup-command: './scripts/startup.sh'
