# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - jwmediaconverter

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
      
      - name: Install dependencies
        run: pip install -r requirements.txt
<<<<<<< HEAD

      - name: Create bin directory
        run: mkdir -p ./app/bin

      - name: Download and extract FFMPEG to app/bin
        run: |
          wget -O ./app/bin/ffmpeg.tar.xz https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-amd64-static.tar.xz
          tar -xf ./app/bin/ffmpeg.tar.xz --strip-components=1 -C ./app/bin
          # Keep only the ffmpeg executable, remove other files
          find ./app/bin ! -name 'ffmpeg' -type f -exec rm -f {} +        
=======
>>>>>>> 4c6eef9c74b79dc494bb34f0fc692fb521c1c7de
        
      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            release.zip
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

<<<<<<< HEAD
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_1AF22C12AFF542D686C783FDD94D454D }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_CBE632E673454ABBB1825B6CDE01281F }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_A336EFB56863462DB53352BEA085CA08 }}
=======
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_1AF22C12AFF542D686C783FDD94D454D }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_CBE632E673454ABBB1825B6CDE01281F }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_A336EFB56863462DB53352BEA085CA08 }}
>>>>>>> 4c6eef9c74b79dc494bb34f0fc692fb521c1c7de

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'jwmediaconverter'
          slot-name: 'Production'
          